#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
# autospec version: v18
# autospec commit: f35655a
#
Name     : pypi-pyclip
Version  : 0.7.0
Release  : 3
URL      : https://github.com/spyoungtech/pyclip/archive/refs/tags/v0.7.0.tar.gz
Source0  : https://github.com/spyoungtech/pyclip/archive/refs/tags/v0.7.0.tar.gz
Summary  : Cross-platform clipboard utilities supporting both binary and text data.
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-pyclip-bin = %{version}-%{release}
Requires: pypi-pyclip-license = %{version}-%{release}
Requires: pypi-pyclip-python = %{version}-%{release}
Requires: pypi-pyclip-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(pywin32)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# PyClip
Cross-platform clipboard utilities supporting both binary and text data.

%package bin
Summary: bin components for the pypi-pyclip package.
Group: Binaries
Requires: pypi-pyclip-license = %{version}-%{release}

%description bin
bin components for the pypi-pyclip package.


%package license
Summary: license components for the pypi-pyclip package.
Group: Default

%description license
license components for the pypi-pyclip package.


%package python
Summary: python components for the pypi-pyclip package.
Group: Default
Requires: pypi-pyclip-python3 = %{version}-%{release}

%description python
python components for the pypi-pyclip package.


%package python3
Summary: python3 components for the pypi-pyclip package.
Group: Default
Requires: python3-core
Provides: pypi(pyclip)
Requires: pypi(pywin32)

%description python3
python3 components for the pypi-pyclip package.


%prep
%setup -q -n pyclip-0.7.0
cd %{_builddir}/pyclip-0.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1723826652
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pyclip
cp %{_builddir}/pyclip-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pyclip/58853eb8199b5afe72a73a25fd8cf8c94285174b || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyclip

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pyclip/58853eb8199b5afe72a73a25fd8cf8c94285174b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
